"use Client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/providers/QueryClientProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-auto`}>
        <QueryClientProvider>{children}</QueryClientProvider>
        <Toaster
          position="top-right"
          duration={2000}
          theme="light"
          richColors
        />
      </body>
    </html>
  );
}
